version: '3.8'

services:
  weibo-proxy:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      # 不再需要/dev/shm映射，Playwright官方镜像已经优化
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Playwright环境变量
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    restart: unless-stopped
    # 移除cap_add和security_opt，使用官方镜像的默认安全设置
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
