version: '3.8'

services:
  weibo-proxy:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - /dev/shm:/dev/shm
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
