version: '3.8'

services:
  weibo-proxy:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      # 不再需要/dev/shm映射，Playwright官方镜像已经优化
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=512
      # Playwright环境变量
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
